# Generated by Django 5.0.4 on 2024-05-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaladministrativo',
            name='id_unidad',
        ),
        migrations.DeleteModel(
            name='UsuarioUnidadTransporte',
        ),
    ]
