# Generated by Django 5.0.4 on 2024-05-14 03:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0002_remove_personaladministrativo_id_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='id_unidad',
        ),
        migrations.RemoveField(
            model_name='unidadtransporte',
            name='detalles_de_ruta',
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='id_rutas',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='TransPorto.rutas'),
            preserve_default=False,
        ),
    ]
