# Generated by Django 5.0.4 on 2024-05-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0003_remove_rutas_id_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadtransporte',
            name='id_rutas',
        ),
    ]
