# Generated by Django 5.0.4 on 2024-05-14 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0004_remove_unidadtransporte_id_rutas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='id_unidad',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='TransPorto.unidadtransporte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='detalles_de_ruta',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
