# Generated by Django 5.0.4 on 2024-05-17 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0008_remove_unidadtransporte_id_rutas_rutas_id_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
