# Generated by Django 5.0.4 on 2024-05-17 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0009_tarjeta_fecha_emision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='id_rutas',
        ),
        migrations.AddField(
            model_name='rutas',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
