# Generated by Django 5.0.4 on 2024-05-19 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0010_remove_rutas_id_rutas_rutas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='id',
        ),
        migrations.AddField(
            model_name='rutas',
            name='id_ruta',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conductores',
            name='informacion_contacto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conductores',
            name='numero_licencia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperativatransporte',
            name='color_vehiculo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cooperativatransporte',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cooperativatransporte',
            name='informacion_contacto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='informes',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='correo_electronico',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='numero_de_telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='direccion_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo_electronico',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numero_telefonico',
            field=models.CharField(max_length=15),
        ),
    ]
