# Generated by Django 5.0.4 on 2024-05-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransPorto', '0011_remove_rutas_id_rutas_id_ruta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutas',
            old_name='id_ruta',
            new_name='id_rutas',
        ),
    ]
